language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8
  - openjdk8

after_success:
- ./gradlew jacocoTestReport coveralls

after_failure:
- cat /home/travis/build/CCob/bittrex4j/build/reports/tests/test/index.html